Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/cancan/matchers.rb'
    - '**/*_spec.rb'

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'gemfiles/vendor/bundle/**/*'

inherit_from: .rubocop_todo.yml
