rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby
  - rbx
gemfile:
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/datamapper_1.x.gemfile
  - gemfiles/mongoid_2.x.gemfile
  - gemfiles/sequel_3.x.gemfile
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
      gemfile: gemfiles/datamapper_1.x.gemfile
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/activerecord_3.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/activerecord_3.1.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/activerecord_3.2.gemfile
notifications:
  recipients:
    - bryan@bryanrite.com
